### ISSUE TITLE
Internal Error on Validator

### ISSUE THREAD

**Issue by cew821** [HHS/ckanext-datajson#12]
When trying to validate [this .JSON file](https://raw.github.com/cew821/va-open-data/master/public-data-listing_2014-02-27_cleaned.json), I'm getting an internal error from the validator:

![image](https://f.cloud.github.com/assets/1237498/2287662/8f154b6e-9fef-11e3-92cd-f054910f2a47.png)

Any thoughts? This is the best POD validator, so I'm bummed I couldn't check my updates with it!

**Comment by JoshData** [comment]
Thanks!

Try now on my development machine: http://54.196.106.25/pod/validate

**Comment by cew821** [comment]
Works on development machine. Thanks for the quick fix!
