### ISSUE TITLE
"format" field type in validator incorrect?

### ISSUE THREAD

**Issue by cew821** [HHS/ckanext-datajson#9]
I got a validation error stating "The 'format' field used to be a string but now it must be an array. (188 locations)" I'm not sure which field that's referring to, but if it's the `format` field, then the schema says it should accept a string containing a MIME type.

I'm guessing this has something to do with the fact that CKAN saves all of it's resources in in the `distribution` object, and `format` is a field that's supposed to travel with that object. 

However for agencies not using CKAN, many of their datasets won't have `distributions` -- they are instead just going to have `accessURL`s, `webService`s along  with a `format` in the first level of the hierarchy.

Either way, the `format` field should never be an array.

**Comment by JoshData** [comment]
Hey. No it means that the value of the format field in your file is a string ("text/plain") when it should be an array of strings (  ["text/plain"] ).

**Comment by cew821** [comment]
Hmmm... I thought [the schema](http://project-open-data.github.io/schema/) says that the format field is supposed to be a string, rather than an array of strings? And that it should be a MIME type.

The validator seems to be validating a separate field called `distribution format` correctly (i.e. a MIME type). But maybe that updated logic never got flowed through to the `format` field?

**Comment by JoshData** [comment]
Ah, well, the schema changed again! I'll have to update the validator.... again. (The format field's example showed a list when I last checked it but it doesn't now.)

**Comment by JoshData** [comment]
Fixed in 7675dbc8737b71abd992046af8fe5ebc9fa8a684. I'll close this issue when this goes live on http://hub.healthdata.gov/pod/validate.

**Comment by JoshData** [comment]
Forgot to close this. The fix has been live for a while.
